name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Bump tag version
      id: bump_tag_version
      run: |
        tag=$(git describe --tags --abbrev=0 2>/dev/null || echo '')
        if [[ -z "$tag" ]]; then
          new_tag="1.0.0"
        else
          major=$(echo $tag | cut -d '.' -f 1)
          minor=$(echo $tag | cut -d '.' -f 2)
          patch=$(echo $tag | cut -d '.' -f 3)
          if [[ $minor == "9" ]]; then
            major=$((major + 1))
            minor=0
          else
            minor=$((minor + 1))
          fi
          new_tag="$major.$minor.0"
        fi
        echo "::set-output name=new_tag::$new_tag"
    - name: Build and push Docker image
      env:
        DOCKER_BUILDKIT: 1
        DOCKER_TAG: ${{ steps.bump_tag_version.outputs.new_tag }}
      run: |
        docker buildx build \
          --platform linux/amd64,linux/arm64 \
          --push \
          --tag mortentabaka/landcover_semantic_segmentation_with_deeplabv3plus:${DOCKER_TAG} \
          --tag mortentabaka/landcover_semantic_segmentation_with_deeplabv3plus:latest \
          .
    - name: Create Git tag
      if: always()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TAG: ${{ steps.bump_tag_version.outputs.new_tag }}
      run: |
        git tag $TAG
        git push origin $TAG

