name: Tag Release

on:
  push:
    branches:
      - main

jobs:
  tag_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create tag
        if: github.event_name == 'push' && contains(github.ref, 'refs/heads/main')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag=$(git describe --tags --abbrev=0)
          tag_number=$(echo $tag | sed 's/0.0.//')
          new_tag_number=$((tag_number + 1))
          new_tag="0.0.$new_tag_number"
          git tag $new_tag
          git push origin $new_tag
