deeplabv3plus_10.0.1:
  dataset_parameters:
    batch_size: 4
    input_image_height: 512
    input_image_width: 512
    number_of_classes: 5
  model_architecture: deeplabv3plus
  model_build_parameters:
    activation_used: softmax
    input_image_height: 512
    input_image_width: 512
    last_layer_frozen: 359
    number_of_classes: 5
    output_stride: 16
    pretrained_weights: cityscapes
    project_version_of_deeplab: original
    were_layers_weights_frozen: true
  model_compile_parameters:
    loss_function: <bound method SemanticSegmentationLoss.soft_dice_loss of <src.features.loss_functions.SemanticSegmentationLoss
      object at 0x7fbc480f3340>>
    metrics:
    - accuracy
    - <src.features.metrics.CustomMeanIoU object at 0x7fbc4fed6250>
    optimizer: <tensorflow.python.keras.optimizer_v2.adam.Adam object at 0x7fbc480f3e80>
  model_name: deeplabv3plus
  revision: 10.0.1
